### ISSUE TITLE
Create enrollment page

### ISSUE THREAD

**Issue by vanathiram** [chingu-voyage6/toucans-team-16#5]
As a member I should be able to book particular dates from the available list of dates 7 days in advance and upto 5pm of the previous day of any working day.
Booking page shows me the availability and dashboard of my previous activity for a term(3 months).
As a member I can see the wait list option and able to book in the wait list when seats are booked for the days.

**Comment by sanjana-1604** [comment]
Please review also created a branch on git repo

**Comment by vanathiram** [comment]
Looks great Sanjana. Lets us proceed further.
